### ISSUE TITLE
"SyntaxError: missing ) after argument list" on Arch Linux with 2.15.x

### ISSUE THREAD

**Issue by frol** [exponent/xde#80]
Trying to start 2.15.0+ releases on Arch Linux (using [`exponent-xde` AUR package](https://aur.archlinux.org/packages/exponent-xde/)) gives me the following crash:

```
App threw an error during load
/usr/share/exponent-xde/app.asar/build/main.js:100
const{app,BrowserWindow,ipcMain}=__WEBPACK_IMPORTED_MODULE_1_electron___default.a;if(__webpack_require__(3)){app.quit();}let mainWindow=null;let projectRoots=[];ipcMain.on('project-opened',(event,projectRoot)=>{console.log(`Opened project at ${projectRoot}`);projectRoots.push(projectRoot);__WEBPACK_IMPORTED_MODULE_6__remote_Menu__["a" /* default */].setupMenu(mainWindow,true);});ipcMain.on('project-closed',(event,projectRoot)=>{console.log(`Closed project at ${projectRoot}`);projectRoots=__WEBPACK_IMPORTED_MODULE_3_lodash___default.a.without(projectRoots,projectRoot);__WEBPACK_IMPORTED_MODULE_6__remote_Menu__["a" /* default */].setupMenu(mainWindow,false);});ipcMain.on('check-for-update',()=>{__WEBPACK_IMPORTED_MODULE_5_electron_updater__["autoUpdater"].checkForUpdates();});ipcMain.on('quit-and-update',()=>{__WEBPACK_IMPORTED_MODULE_5_electron_updater__["autoUpdater"].quitAndInstall();});app.on('window-all-closed',()=>{app.quit();});app.on('will-quit',async
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:280:12)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:322:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
A JavaScript error occurred in the main process
```

I understand that this is not the supported way of installing, but since 2.14.3 release works fine, I thought I would better ask you if something has changed since then.

**Comment by frol** [comment]
OK, I figured it out. You rely on the Electron 1.6, which is only a beta at the moment, and Arch Linux has the latest stable 1.4.15 version.

**Comment by DrawnWren** [comment]
I upgraded to Electron 1.6.2, reinstalled, and am still getting this error. Can you confirm how you solved this?

**Comment by frol** [comment]
@DrawnWren I don't recall exactly, but I might have just installed it with `npm install xde` in a temporary folder and run it as `./node_modules/.bin/xde` (or something along these lines)

**Comment by DrawnWren** [comment]
For any future readers, I ended up using the binary from expo.io but the npm option might be a good idea.
